name: dartter
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: ^3.0.5

dependencies:
  dargon2: ^3.2.1
  dart_jsonwebtoken: ^2.8.2
  dartseid: ^0.0.9+2
  dartseid_config: ^0.0.2
  dartseid_views: ^0.0.4
  envied: ^0.3.0+3
  get_it: ^7.6.0
  injectable: ^2.1.2

dependency_overrides:
  dartseid:
    path: ../dartseid_repo/packages/dartseid

dev_dependencies:
  build_runner: ^2.4.6
  envied_generator: ^0.3.0+3
  injectable_generator: ^2.1.6
  lint: ^2.1.2
  test: ^1.21.0
